### PR TITLE
[RFC] Existing libraries: try [abandoned] tag.

### PR DESCRIPTION
**Pull request by stanislaw**

### CODE REVIEW

**Comment by stanislaw** [comment]
Open to suggestions on how to improve the visual appearance 😄

**Comment by stanislaw** [comment]
Immediate conclusion: not clear how to differentiate `[abandoned]` from `[prototype]` so I only used one tag.

**Comment by stanislaw** [comment]
We can see that the [list](https://github.com/stanislaw/mutation-testing/blob/0eaa41a92bef8e30b9ff15d7a7294bac6cd3af7c/README.md) now gives us the following stats:

11 out of 23 tools are abandoned, given I only used the date of the last update in a repo as a criterion.

**Comment by theofidry** [comment]
Cheers :)

**Pull request merged**
