### PR TITLE
Existing libraries / C/C++: accmut.

### PR DESCRIPTION
**Pull request by stanislaw**

### CODE REVIEW

**Comment by theofidry** [comment]
I really wonder how you do to find all of them :P

In any case it's quite cool, I'll have to read those papers :)

**Comment by stanislaw** [comment]
> I really wonder how you do to find all of them :P

We are writing the paper about our Mull. Most of the tools come from either random googling mutation*-related keywords on the internet or from looking at Github's topic "mutation-testing" sorted by the last update.

**Comment by stanislaw** [comment]
For example, there is a tool on R language, but I didn't have time to look at it closer. Should probably be added to the list.

**Comment by theofidry** [comment]
I'll have to have an extensive look at some point as well when I'll get deeper into Infection for PHP. I'm amazed by the number of tools but somehow the adoption is quite low which hints on the impracticality of them. Gotta work on that :)

**Pull request merged**
